<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Key' => '',
    'Company ID' => '',
    'Created At' => '',
    'Email' => '',
    'ID' => '',
    'Name' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Status' => '',
    'Updated At' => '',
    'Username' => '',
    'Balance: {0,number,,000,000000}' => '@@@@',
    'Example of string with \'\'-escaped characters\'\': \'{\' \'}\' \'{test}\' {count,plural,other{\'\'count\'\' value is # \'#{}\'}}' => '@@@@',
];
